### ISSUE TITLE
How to get IP address from fields "addr_0", "addr_1" collection "hosts" in MongoDB?

### ISSUE THREAD

**Issue by ubushan** [cea-sec/ivre#1081]
### IVRE Version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15

Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]

Linux IVRE 5.4.0-1031-azure #32-Ubuntu SMP Tue Oct 6 09:47:33 UTC 2020 x86_64

Dependencies:
    Python module pymongo: 3.7.2
    Python module py2neo: missing
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 3.2.1
    Python module krbV: missing
    Python module PIL: 8.0.1
    Python module MySQLdb: missing
    Python module dbus: 1.2.16
    Python module matplotlib: missing
    Python module bottle: 0.12.19
    Python module OpenSSL: 19.1.0
    Python module tinydb: missing

### Summary

Hello!
How to get IP address from fields "addr_0", "addr_1" collection "hosts" in MongoDB? Or there are other way for get IP address?

![image](https://user-images.githubusercontent.com/12890432/106131369-a4dcd000-6173-11eb-90d5-7df50352dbf9.png)

Thanks.

**Comment by p-l-** [comment]
How do you get those results? MongoDB records are not supposed to be accessed outside of IVRE (they should only be used through the IVRE API, potentially exposed via the IVRE Web server).

The internal format used in the MongoDB storage (or other backends) may vary, and the Python functions keep the results consistent; this is what happened when the `"addr"` field has been changed to two "sub-fields" in the first place (so that we can have IPv6 addresses stored in IVRE).

If you use the standard `db.<purpose>.get(<filter>)` the IP address should be in the `"addr"` field, and the `"addr_0"` and `"addr_1"` fields should not exist (if that is not the case, it is a bug in IVRE).
