### ISSUE TITLE
I can not go to the next page by the upper left corner of the page navigation on web interface

### ISSUE THREAD

**Issue by duolaaa** [cea-sec/ivre#201]
hi ,there !
first,When I finished the installation and deployment,Importing scan data,i found that I can not go to the next page by the upper left corner of the page navigation on web interface, can you help ,think you !
second, is there any way to directly manipulate the database .
think you very much .

**Comment by p-l-** [comment]
Hi,

First: this is a bug and should be fixed by #202. Can confirm that the provided patch fixes your issue?

Second: not from the Web interface. You can either use the Python API (with the `db` object from the `ivre.db` module), or from a Mongo shell.

With the Python API, if you want to work on the Nmap database, you can start with:

    >>> from ivre.db import db
    >>> help(db.nmap)
    [...]

**Comment by duolaaa** [comment]
First of all, thank you for the timely reply to me . i am sorry to tell you ,this method does not solve my first problem . My environment using docker way to build, so i download the controllers.js replace ivreclient container of the same file (root@93902ad83dc0:/usr/local/share/ivre/web/static/ivre/controllers.js) .  Am I in the right way ?

**Comment by p-l-** [comment]
You should replace the file in the `ivreweb` container instead (since the files are served from this container, and then force a full reload of IVRE's main page (to make sure all the files, including `controllers.js`, are reloaded).

**Comment by p-l-** [comment]
I have merged #202 since it fixes a bug (even if it might not be *your* bug, I need this patch anyway). So new Docker images are being built and should be ready within minutes; this will allow you to test by just `docker pull`-ing the new images.

If that fixes your bug, please leave a comment here; if that does not fix your bug, please re-open this issue.

**Comment by duolaaa** [comment]
Hi, I use a new Docker images can solve the problem, but replace controllers.js failed, may be replaced by wrong,  in short, thank you very much for your help,have a  nice day !

**Comment by p-l-** [comment]
Thanks for your report @duolaaa!
