### ISSUE TITLE
ERROR: Could not import ivre. Check the server's logs!

### ISSUE THREAD

**Issue by duolaaa** [cea-sec/ivre#320]
HI, i installed ivre by 'FAST-INSTALL-AND-FIRST-RUN.md' , then hava a error when i visite the web interface. the error is `ERROR: Could not import ivre. Check the server's logs!` , i didn't find the server's log in /var/log . and i found `Forbidden You don't have permission to access /dokuwiki/doc:webui on this server.` i used the apache default configuration .i am very grateful that you can tell me how can i sove this problems .

**Comment by fjavierc** [comment]
Hi Duolaaa;

For the message of the Wiki (_Forbidden! You don't have permission to access /dokuwiki_ ), depending on how you have installed Ivre, you can only  access  from localhost (127.0.0.1) . You need to change the ACLS to allow access to those IPs you want.

For example, to allow access to the Wiki only from your PC, you need ( if you installed Ivre on Debian):

1- Edit /etc/apache2/conf-available/dokuwiki
`root@server:~# vi /etc/apache2/conf-available/dokuwiki.conf`

2- Change ACL. You can add new single ACL. In this case, I allow the access from 192.168.100.121.
```
... text...text...
AllowOverride All
order allow,deny
     Allow from localhost 127.0.0.1 ::1
     Allow from 192.168.100.121               #New acl.
...
```

3-  Restart Apache
`root@server:~# service apache2 reload`

Remember, all this is if you have installed Ivre in Debian. If you've done in other distribution, you  must configure Apache so that dokuwiki is accessible from your pc.

On the other error (could not be imported Ivre), I understand that you are stating that you review server logs, not the "server.log". With so little information, I think you should check the logs of Apache (/var/log/apache2/error.log) although it could be that you have skipped some step.

From your server (where you have installed Ivre) , Can you  run ivre command to scan hosts or import results of a nmap?, Do you get any error?

**Comment by duolaaa** [comment]
i am  so sorry , I did not consider dokuwiki'config for the error, now i change the rules to Allow from all ,its work . the other error ,i soved it by visit `http://stackoverflow.com/questions/2192323/what-is-the-python-egg-cache-python-egg-cache` . now ivre works well ,thank you for replay ,have a nice day.

**Comment by p-l-** [comment]
Thanks @fjavierc!

**Comment by naisanza** [comment]
@fjavierc this would be great to have in the documentation

**Comment by naisanza** [comment]
@fjavierc I set it to

```
Allow from all
```
But it looks like it's not running the PHP

![screenshot from 2017-09-30 19-21-35](https://user-images.githubusercontent.com/1614425/31050308-aa55f7b4-a614-11e7-9c50-fd44923784bf.png)

**Comment by p-l-** [comment]
@naisanza you have to install and configure PHP. That's a Dokuwiki / web server issue, not an IVRE issue.

**Comment by naisanza** [comment]
@p-l- I think that's missing from the main documentation? I didn't see it anywhere as a requirement

**Comment by p-l-** [comment]
@naisanza Dokuwiki is a dependency that you have to install following its own documentation. #422 makes that clearer.

**Comment by naisanza** [comment]
@p-l- ah I see. The troubles with having so many external dependencies, is trial and error

**Comment by p-l-** [comment]
@naisanza that's an optional dependency. Also, it's better IMO to use something that exists and works than to write a poor, specific, non-reusable replacement.

**Comment by naisanza** [comment]
@p-l- Not writing something new, but just trial and error when it comes to installing something with many dependencies . I suppose that's just a part of how these things are
