### ISSUE TITLE
First time running Ivre. Scan2DB complained "is a directory"

### ISSUE THREAD

**Issue by runatyr** [cea-sec/ivre#377]
Hello all.
Forgive me if this is a basic quetion. I am a network person by experience not a coder/developer

I was unable to get ivre working on my linux ditro until I went back and ran it as root (yes I know this is taboo... I am going adjust permissions shortly)

Once I followed the instructions at
https://github.com/cea-sec/ivre/blob/master/doc/FAST-INSTALL-AND-FIRST-RUN.md

I used Vagrant and Docker and have them up and running

I kicked off...# ivre runscans --routable --limit 1000

When I went back to run the next command I keep getting
root@10c32db250fe:/# ivre scan2db -c ROUTABLE,ROUTABLE-CAMPAIGN-001 -s MySource -r > scans/ROUTABLE/up/
**bash: scans/ROUTABLE/up/: Is a directory**

What basic ingredient am I missing?

thank you all 
-runatyr

**Comment by fmonjalet** [comment]
Hi,

Yes, I think there was a misunderstanding of the doc, the `>` was not part of the command but only something that looks like a real prompt new line. (Actually, the error you see is because you are trying to redirect the command's stdout to a directory.)

The command you are looking for is : `ivre scan2db -c ROUTABLE,ROUTABLE-CAMPAIGN-001 -s MySource -r scans/ROUTABLE/up/`

Cheers,
Florent
