### ISSUE TITLE
Cannot import ivre.db.neo4j

### ISSUE THREAD

**Issue by secnum** [cea-sec/ivre#727]
### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.13.dev35

Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

Linux ivre 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.8.0
    Python module py2neo: 4.3.0
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.17
```
### Summary

Python error after `ivre flowcli --init`.

### Expected behavior

No Python traceback should occurs.

### Actual behavior

$ ivre flowcli --init
This will remove any flow result in your database. Process ? [y/N] y
ERROR:ivre:Cannot import ivre.db.neo4j for neo4j://neo4j:neo4j@localhost:7474/
Traceback (most recent call last):
  File "/home/alexandre/ivreenv/lib/python3.6/site-packages/ivre/db/__init__.py", line 2543, in get_class
    module = __import__('ivre.db.%s' % modulename).db
  File "/home/alexandre/ivreenv/lib/python3.6/site-packages/ivre/db/neo4j.py", line 38, in <module>
    from py2neo import http
ImportError: cannot import name 'http'
Traceback (most recent call last):
  File "/home/alexandre/ivreenv/bin/ivre", line 84, in <module>
    main()
  File "/home/alexandre/ivreenv/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/home/alexandre/ivreenv/lib/python3.6/site-packages/ivre/tools/flowcli.py", line 106, in main
    db.flow.init()
AttributeError: 'NoneType' object has no attribute 'init'

### How to reproduce

Launch `ivre flowcli --init`.

### More

//

**Comment by p-l-** [comment]
Hi,

Thanks for your report.

For now, the default (and only) backend for ``flow`` is Neo4j. This is about to change and we plan to remove Neo4j support (and switch to MongoDB, see #685).

We only support py2neo 3.x (see the `requirements.txt` and `setup.py` files, as well as [the documentation](https://doc.ivre.rocks/en/latest/install/installation.html#python).

Your version output shows you have py2neo 4.3.0 installed, which is why this is broken.

Please do not hesitate to re-open this issue if needed.
