### ISSUE TITLE
Long time to run runscans --routable command

### ISSUE THREAD

**Issue by Allard-Chris** [cea-sec/ivre#822]
### IVRE Version
```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.14.dev53

Python 2.7.17rc1 (default, Oct 10 2019, 10:26:01) 
[GCC 9.2.1 20191008]

Linux grehack 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.7.1
    Python module py2neo: missing
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.15
    Python module OpenSSL: missing
```

### Summary
Hello everyone,
I would like to know if it's normal to get a long time to scan only 40 ip.
For me, it's take 7 minutes with this results :

```
ADDING TARGET 1 : 50.84.195.14
ADDING TARGET 2 : 104.39.161.157
ADDING TARGET 3 : 203.2.4.56
ADDING TARGET 4 : 61.139.235.207
ADDING TARGET 5 : 138.122.238.18
ADDING TARGET 6 : 184.24.19.113
ADDING TARGET 7 : 220.44.91.28
ADDING TARGET 8 : 198.65.96.131
ADDING TARGET 9 : 154.81.195.86
ADDING TARGET 10 : 36.52.247.133
ADDING TARGET 11 : 85.246.149.64
ADDING TARGET 12 : 45.62.58.247
ADDING TARGET 13 : 155.141.19.90
ADDING TARGET 14 : 154.16.82.217
ADDING TARGET 15 : 82.34.150.164
ADDING TARGET 16 : 86.241.219.43
ADDING TARGET 17 : 216.166.161.30
ADDING TARGET 18 : 195.189.149.237
ADDING TARGET 19 : 68.55.153.200
ADDING TARGET 20 : 193.156.222.159
ADDING TARGET 21 : 195.151.40.162
ADDING TARGET 22 : 221.76.109.65
ADDING TARGET 23 : 104.240.75.44
ADDING TARGET 24 : 214.4.157.211
ADDING TARGET 25 : 160.124.0.102
ADDING TARGET 26 : 94.95.156.213
ADDING TARGET 27 : 70.94.212.208
ADDING TARGET 28 : 222.204.150.71
ADDING TARGET 29 : 187.5.155.106
ADDING TARGET 30 : 97.211.14.169
ADDING TARGET 31 : 3.239.110.52
ADDING TARGET 32 : 81.72.253.251
ADDING TARGET 33 : 121.248.13.174
ADDING TARGET 34 : 91.131.90.61
ADDING TARGET 35 : 17.17.72.216
ADDING TARGET 36 : 69.237.153.239
ADDING TARGET 37 : 61.186.87.50
ADDING TARGET 38 : 141.82.61.17
ADDING TARGET 39 : 160.90.43.60
ADDING TARGET 40 : 45.16.92.163
WROTE ALL TARGETS
NO MORE DATA TO PROCESS
```
It's run on a fresh ubuntu server with 4Go RAM and a I5-8265U.
The provider is Orange Fiber 1Go
I followed this page for the installation : https://doc.ivre.rocks/en/latest/install/fast-install-and-first-run.html
Thanks in advance.

### How to reproduce

sudo ivre runscans --routable --limit 40

**Comment by p-l-** [comment]
This is probably normal: Nmap can be very slow to scan hosts on the Internet, for various reasons (slow connections, buggy NSE scripts, etc.).

One way to make scans faster is to use the `--output=XMLFork --processes=<n>`, where `<n>` is the number of Nmap process you want to run in parallel. This should not be necessary, since Nmap is supposed to know how to use the network resources, but I have used this successfully a lot, particularly against random hosts across the Internet.

If you want to scan the whole IPv4 addresses (and not just "some" random hosts), I would strongly advice the use of Masscan. You will get less detailed in your results (NSE scripts are an important source of intelligence), but you will get comprehensive Internet scans.

**Comment by Allard-Chris** [comment]
Hi,

Thanks for your reply.
For me, it was  not normal to wait 7 minutes for 40 publics IPs when the example in the Fast install guide said for 1000 IP (sudo ivre runscans --routable --limit 1000).

Regards,

Chris.
