### ISSUE TITLE
WebUI: completion/help broken for some filters

### ISSUE THREAD

**Issue by p-l-** [cea-sec/ivre#85]
The tooltip disappears for filters with an optional argument when typing ":". Example: "screenwords:".

**Comment by commial** [comment]
Since 7d3d7326, the function `prepare` (`help.js`, line 21) is responsible for optional case management.

As for `!` suffix, an automatic handling could be done based on the command description. Maybe thanks to the string `<b>(:`, if you consider it enough.

For now, it highlights `smbshare`, `cpe`, `screenshot` and `screenwords`. As `:` is already a suffix, one just have to add a new entry for each of those elements, ended with a `:`.

If you agree with this, I can submit a patch.

**Comment by p-l-** [comment]
Agreed. Add `sshkey` to this list ;-) .
