### ISSUE TITLE
Scan results didn't showed up on Web Interface

### ISSUE THREAD

**Issue by Senanfurkan** [cea-sec/ivre#875]
I am sorry if this is a very noob question but I am trying to figure out how to use the ivre(It is very similar to my personal project so) 
But I think I couldn't use it properly. My first try end up like mess.

### IVRE Version

```
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.14

Python 3.7.3 (default, Oct  7 2019, 12:56:13) 
[GCC 8.3.0]

Linux 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.10.1
    Python module py2neo: missing
    Python module sqlalchemy: 1.2.15
    Python module psycopg2: 2.8.4 (dt dec pq3 ext lo64)
    Python module krbV: missing
    Python module PIL: 5.4.1
    Python module MySQLdb: missing
    Python module dbus: 1.2.8
    Python module matplotlib: missing
    Python module bottle: 0.12.18

```

### Summary

I am not be able to see the scan results on the Web Interface.

### Expected behavior

It should have worked, I followed the manuel exactly. Also there are some records in the database. When I type `ivre scancli --port 80`, I see some outputs. But only in the console.

### Actual behavior
No data showed up on the Web interface. It is only a white page with some menus.

### How to reproduce

You can see yourself, I made it public as a copy.
`http://165.22.130.67/`

### More
I used the command below to import the data

```
ivre scan2db -c ROUTABLE,COMPANY -s MySource -r scans/FILE-ips.txt/up
WARNING:ivre:Cannot find Maxmind database files
415 results imported.
```

```
ivre db2view nmap
```

**Comment by p-l-** [comment]
Hi,

Thanks for your interest in IVRE!

First of all, `ivre scancli --port 80` is not the best way to know if results should be displayed or not, since it uses the "nmap" purpose, while the Web UI uses the "view" purpose (see [purposes in the documentation](https://doc.ivre.rocks/en/latest/overview/principles.html#purposes) if you are not sure to understand what I mean). `ivre view --port 80` would use the same "view" purpose as the Web UI.

To understand what is happening here, you should use the developer tools (using the F12 key), network tab.

Based on what I can see from your public server, the hits on the IVRE application (as opposed to those on static files) under `/cgi/` all fail with a "500 internal server error". You will probably have more information in Apache's error logs. Could you have a look a them and report the relevant parts here?

Thanks!

**Comment by Senanfurkan** [comment]
Hello, 
Thanks for your amazingly fast reply ! 

You are right ! I saw the error in my apache logs. It looks like `pip install bottle` command installed it for python3.7. 

I solved the error by installing it as python2.7

For those who stucks with same mistake;

```
python2.7 -m pip install bottle
```

**Comment by p-l-** [comment]
Perfect! Happy scanning and let us know if you have any other issue.
