### ISSUE TITLE
Collect http body

### ISSUE THREAD

**Issue by lprat** [cea-sec/ivre#933]
Hi,

I would like to know if IVRE allows the collection and the search of http body ?
Only filters httphdr, http title & auth exist (cf: https://doc.ivre.rocks/en/latest/usage/web-ui.html#command-specification).
I would like to known if exist way to collect and search them?
I thinking use NSE script nmap to extract http body and export in XML format to import in Ivre. I dont known if possible to search with filter "script:nse_name:/regex/" to check info in body http (from nse script)?

Thank for your help.

**Comment by p-l-** [comment]
Hi,

Thanks for your interest in IVRE and your question!

There are two parts in your question:
- is Nmap able to collect HTTP content?
- if so, is IVRE able to access such content?

Since IVRE is not itself a scanner, you need to get the HTTP content from the scanner you use. With Nmap, yes, an NSE script seems a good option to me, but I'm no Nmap expert and you should probably ask your question to the Nmap project.

Once you have the data collected in your scan result, if it is in a script output, then yes, you can query `script:[script_name]:/content_regexp/`.

I hope this helps, I'm closing this issue but please do not hesitate to re-open it if you need more information.

**Comment by p-l-** [comment]
See the entry [Can IVRE be used to look for XXX?](https://doc.ivre.rocks/en/latest/overview/faq.html?highlight=FAQ#can-ivre-be-used-to-look-for-xxx) from the FAQ.
